### PR TITLE
DependentLookupFieldHandler: Support ID and InternalName (#807)

### PR DESCRIPTION
**Pull request by sebastianmattar**
Fix for #807:
- Rewrote DependentLookupFieldHandler to have control over which ID and InternalName will be used
- Minor refactoring regarding field lookups
- Implemented Test "CanDeploy_DependentLookupField_OnList"
- Could not get "CanDeployRandom_DependentLookupFieldDefinition" to pass in CSOM, can you have a look?

### CODE REVIEW

**Comment by SubPointSupport** [comment]
Sure, will do. What's the issues with passing random test in CSOM?

**Comment by sebastianmattar** [comment]
Can't get field update validation to work for some fields. 
I am pretty sure the code itself is working as my manual tests are successful.

**Comment by SubPointSupport** [comment]
Thanks, will have a look. No worries.

**Comment by SubPointSupport** [comment]
Both CSOM and SSOM tests fail - the regression tests, and the fields show nothing in the UI. Checking.

**Comment by SubPointSupport** [comment]
SSOM is fine. Overlooked it. Sorting out the CSOM one. Will be updating https://github.com/SubPointSolutions/spmeta2/issues/807 as needed.

**Pull request merged**
