### PR TITLE
View.Aggregations and View.AggregationsStatus

### PR DESCRIPTION
**Pull request by andreasblueher**
I'm not sure if my changes to ClientListViewDefinitionValidator.cs are correct, but I'm pretty certain.

### CODE REVIEW

**Comment by andreasblueher** [comment]
Sorry for all the reverts and commits, but I had a couple of issue getting my branch up2date. I had written my changes for an old version and when I first commited I had deleted some changes which where made in the mean time.

**Comment by andreasblueher** [comment]
I'm sorry, but Git and me are still no friends. Could you please tell me if you can still see my changes?

**Comment by SubPointSupport** [comment]
Sure, can clearly see all the changes :)

**Comment by SubPointSupport** [comment]
Looks excellent, thank you @andreasblueher 

We''l merge, test and add BuiltInAggregationsStatus as On/Off. MSDN goes with pure string on it, so built-on value would be nice to have.

**Pull request merged**
