### PR TITLE
Add SPView fields InlineEdit and TabularView (SSOM only)

### PR DESCRIPTION
**Pull request by sebastianmattar**

### CODE REVIEW

**Comment by SubPointSupport** [comment]
Great work, @sebastianmattar 
Seems like you spent quite a time with the M2 source code.

**Comment by andreasblueher** [comment]
Hey @sebastianmattar,

good work.

One suggestion from my side, since "InlineEdit" only works if set to true or false, wouldn't it be nice to have that one as a bool property and setting it correctly in the handler? Although it might be confusing, it would be the safer solution regarding false entries. Else you might add an other issue regarding a validation for this field.

**Comment by sebastianmattar** [comment]
Hi Andreas,

thank you! 

I initially planned to map the InlineEdit field to bool but figured it can be a valid requirement to set it to null, e.g. in SP2010/2013 migration scenarios.
Therefore I propose to not change the data type but to extend validation to check for the strings "true", "false" or null.

**Comment by andreasblueher** [comment]
By default all bool properties are nullable in SPMeta2 so you could have all those options. But I don't see any reason why validating the property wouldn't be enough.

**Comment by SubPointSupport** [comment]
Correct, we tend to introduce new properties as nullable types to ensure backward compatibility.

The thing has to do with the previous versions of M2, old models and serialization / deserialization.
Think that way: you have a model without "new props", without "InlineEdit" prop and provision does not do anything with it. You migrate to a new version of M2, and now you have "InlineEdit" - that's fine, but  it has true / false value by default and CAN impact existing provision or MAY have an impact on the desired configuration. 

Mean, we did not ask to have new properties setup with new M2 version, too risky and unpredictable, that's why new props are introduces as nullables most of the time unless they HAVE to have set with some initial values.

Hope that makes sense, we'll update InlineEdit with bool?, no worries.

Also, @sebastianmattar, don't miss our Yammer Network, just in case:
https://www.yammer.com/spmeta2feedback#/home

**Comment by sebastianmattar** [comment]
I agree with the bool? type being nicer but its more complicated than that as there are four scenarios:
1. Do not update the field (should be the default which it currently is not)
2. Set the field to null (required for migrated SP2010 lists in SP2013, not tried it myself though)
3. Set the field to "true"
4. Set the field to "false"

**Comment by SubPointSupport** [comment]
What's the thing with setting field to null? Why is it required while migrating from 2010 to 2013?

**Comment by sebastianmattar** [comment]
I found this blog article describing the issue: http://www.vlieshout.net/disable-inline-editing-on-migrated-sites/

**Comment by SubPointSupport** [comment]
Thanks for the context, that makes more sense.

We'd like ignore this case. Better to write some PS script or C# console app to fix that migration issue.
M2 already has tons of SharePoint API fixes here and there, having one really rare case wouldn't be a valuable addition.

**Comment by sebastianmattar** [comment]
I agree and updated the code.

**Comment by SubPointSupport** [comment]
Synced. We going to test / close as much as we can from https://github.com/SubPointSolutions/spmeta2/milestones/SPMeta2%201.2.60,%20February%202016 iteration and push the release early this week.

Thanks again for your effort, @sebastianmattar

**Pull request merged**
