### PR TITLE
Fix NullReferenceException in ManagedPropertyModelHandler

### PR DESCRIPTION
**Pull request by andreasblueher**
There was a NullReferenceException when you try to use a CrawledProperty which doesn't exists. I've fixed the code, but you might want to throw a more specific exception like (CrawledProperty not found) so the developer gets feedback on whats going on.

### CODE REVIEW

**Comment by andreasblueher** [comment]
I don't know how I could have excluded those "Test lokal" commits, but since it's reverted, it shouldn't do any harm.

**Comment by SubPointSupport** [comment]
That's the test case for that? How to reproduce that null-ref exception and what might the model look lke?

**Comment by andreasblueher** [comment]
This is the code I executed to get the error. Whenever you try to assign a mapping for a crawled property which doesn't exist to the mappings property of a ManagedPropertyDefinition you'll get a null reference exception.

var mapping = new ManagedPropertyMappping
{
	CrawledPropertyName = "anything_"
};

var propertyDefinition = new ManagedPropertyDefinition();
propertyDefinition.Name = "NewTestPropertyDefinition";
propertyDefinition.ManagedType = "Text";
propertyDefinition.Mappings = new List<ManagedPropertyMappping> { mapping };

var farmModel = SPMeta2Model.NewFarmModel(farm =>
	farm
		.AddManagedProperty(propertyDefinition)
	);

var ssomProvisionService = new StandardSSOMProvisionService();
ssomProvisionService.DeployFarmModel(currentFarm, farmModel);

**Comment by SubPointSupport** [comment]
Confirming the bug, added CanDeploy_ManagedProperty_WithWrongCrawledProperty_OnFarm() test along with the others:

* CanDeploy_ManagedProperty_OnSite
* CanDeploy_ManagedProperty_OnFarm
* CanDeploy_ManagedProperty_WithWrongCrawledProperty_OnFarm

**Pull request merged**
