### PR TITLE
Added support for EnableThrottling for SSOM

### PR DESCRIPTION
**Pull request by andreasblueher**
I took the liberty to add support for SPList.EnableThrottling based on this yammer feedback. Since this was an easy fix, I went ahead to implemented it to get back into SPMeta2 ;-).

https://www.yammer.com/spmeta2feedback/#/threads/show?threadId=779699365

(not sure how I can remove all those private commits from pull requests, because with time this could get very messy.

### CODE REVIEW

**Comment by SubPointSupport** [comment]
We so much don't want to add that SSOM only property to the library.
Posted temporary solution at yammer:
```cs
web.AddList(listDef, list => {

list.OnProvisioning<SPList, ListDefinition>(context =>
{
context.Object.EnabledThrottling = true;
});
});

```
SPMeta2 has "event" before/after artifact provisioning. You need to type it correctly, and the use the following namespace:
using SPMeta2.Syntax.Default.Modern;

context.Object will be your list instance after provision but before updating.
Be aware that such event wouldn't be serialized and work differently across SSOM/CSOM.

Will have a look on the pull request later.

**Comment by SubPointSupport** [comment]
Tracked https://github.com/SubPointSolutions/spmeta2/issues/908

**Comment by SubPointSupport** [comment]
Hmm, why to close?

**Comment by andreasblueher** [comment]
Hmmmm, this has to have something to do with the fact that I rebased my development branch (due to all the commits ahead of your dev). Didn't think of this pull request being related to one of those commits. So I guess it's gone :)

I could recreate the code (since it wasn't too much work), but since you suggested another solution without bloating the definition I'm not sure.

**Comment by SubPointSupport** [comment]
Oh, right. Leave it, then. We'll get another go.

The thing is that we don't see a value in adding props that aren't on both CSOM/SSOM and aren't commonly used. Sometimes we add then for SSOM only implementation but CSOM lacks it. That puzzles people as M2 starting having deviation in behaviour. As far as event help, we tend to avoid adding more mess in already messy API :)

**Pull request closed without merging**
