### PR TITLE
Fix #807: DependendLookupFieldHandler now uses ID and InternalName properties

### LINKED ISSUE #807: DependentLookupFieldDefinition: Id is not used
DependentLookupFields will be created with random field Ids.

            var leadRecords = new ListDefinition
            {
                Title = "Lead Records",
                Description = "A generic list.",
                TemplateType = BuiltInListTemplateTypeId.GenericList,
                CustomUrl = "m2LeadRecordsList"
            };

            var leadRecordTypes = new ListDefinition
            {
                Title = "Lead Record Types",
                Description = "A generic list.",
                TemplateType = BuiltInListTemplateTypeId.GenericList,
                CustomUrl = "m2LeadRecordTypesList"
            };

            var leadTypeLookup = new LookupFieldDefinition
            {
                Title = "Lead Type",
                InternalName = "m2LeadType",
                Group = "SPMeta2.Samples",
                Id = new Guid("FEFC30A7-3B38-4034-BB2A-FFD538D46A63"),
                LookupListTitle = leadRecordTypes.Title,
                AddToDefaultView = true
            };

            var leadTypeIDDependentLookup = new DependentLookupFieldDefinition
            {
                Title = "Lead Type:ID",
                InternalName = "m2LeadTypeID",
                Group = "SPMeta2.Samples",
                Id = new Guid("FEFC30A7-3B38-4034-BB2A-FFD538D46A64"),
                PrimaryLookupFieldId = leadTypeLookup.Id,
                LookupField = BuiltInInternalFieldNames.ID,
                AddToDefaultView = true
            };

            var webModelLookupTargetList = SPMeta2Model.NewWebModel(web =>
            {
                web
                  .AddList(leadRecordTypes);
            });

            var webModelLookupList = SPMeta2Model.NewWebModel(web =>
            {
                web
                  .AddList(leadRecords, list =>
                  {
                      list.
                        AddField(leadTypeLookup)
                       .AddField(leadTypeIDDependentLookup);
                  });
            });

            // deploy the model to the SharePoint site over CSOM
            var csomProvisionService = new CSOMProvisionService();
            csomProvisionService.DeploySiteModel(clientContext, webModelLookupTargetList);
            csomProvisionService.DeploySiteModel(clientContext, webModelLookupList);

### PR DESCRIPTION
**Pull request by sebastianmattar**
- Rewrote DependendLookupFieldHandler to have control over which ID and InternalName will be used
- Minor refactoring regarding field lookups
- No regression testing performed yet

### CODE REVIEW

**Comment by SubPointSupport** [comment]
"Setting the index property will throw an exception for dependent lookup" <-- hmm... this is interesting, nice pick up @sebastianmattar 

Going to have a look and run tests, thanks!

**Comment by sebastianmattar** [comment]
I managed to get the regression tests up and running and I see that lots of test fail. If you can wait a bit I try to fix this

**Comment by SubPointSupport** [comment]
What are they? What are the exceptions?

The following should pass on both CSOM / SSOM:
CanDeployRandom_DependentLookupFieldDefinition
CanDeploy_DependentLookupField_OnSite
CanDeploy_DependentLookupField_OnContentType

CanDeployRandom_DependentLookupFieldDefinition generates a random definition via DependentLookupFieldDefinitionGenerator  (seems it should be updated with ID / Guid) and deploys the field multiple times. PrimaryLookupField from DependentLookupFieldDefinitionGenerator  is used every time as a source.

The following weren't implemented, meaning currently DependentLookupField can't be deployed under web and list scopes. The should NOT pass, they should fail.
CanDeploy_DependentLookupField_OnWeb
CanDeploy_DependentLookupField_OnList

**Comment by SubPointSupport** [comment]
The rest of tests depend on particular case, there are tons of tests on fields, various field types, props, lookups and scenarios, some for lookups as well. We'll get back Monday or tomorrow, we'll see how it goes.

**Comment by sebastianmattar** [comment]
Thank you! 
There were some issues with my code and regression tests were a big help in fixing them.

**Comment by SubPointSupport** [comment]
Great to hear that, let us know once you stuck. Will sort it out together.

Would you create a new pull request instead of thins one? Guess this one can be closed as you mentioned you were to sort out fixes. Correct?

**Comment by sebastianmattar** [comment]
I agree, I will create a new pull request once I am ready.

**Comment by SubPointSupport** [comment]
Thanks, have fun :)

**Pull request closed without merging**
